### ISSUE TITLE
ERB site files so you can have ENV variables in them

### ISSUE THREAD

**Issue by orieken** [hammernight/taza#22]
came across this issue today I am building an env with vms and then clients to test those vms all on the fly. 
```yaml
standalone:
    :url: <%= "#{ENV['STANDALONE_URL']}" %>
```

so If I could erb the site.yml it would make it easier for me to just pass in the new url and information via the command line. when I trigger them to run. 

```bash
cucumber TAZA_ENV=standalone BROWSER=chrome STANDALONE_URL=latest.env.com
```

it would be changing this line 
https://github.com/hammernight/taza/blob/master/lib/taza/settings.rb#L26
```ruby
YAML.load_file(File.join(config_folder,"#{site_name.underscore}.yml"))[ENV['TAZA_ENV']]
```
to this

```ruby
YAML.load(ERB.new(File.read(File.join(config_folder,"#{site_name.underscore}.yml"))).result)[ENV['TAZA_ENV']]
```

**Comment by uchagani** [comment]
Fixed by #30
