### ISSUE TITLE
Unable to create the project using taza gem

### ISSUE THREAD

**Issue by farooq33** [hammernight/taza#26]
Hi Team,

I tried with the following command but unable  to create the folder,I got the error as below,

taza google

"Could not find command "google".

**Comment by farooq33** [comment]
I ran the above command in Windows 7

**Comment by uchagani** [comment]
you have to provide a command.  I think what you meant to type  ```taza create google```

**Comment by farooq33** [comment]
C:\>taza create sampl
      create  akefile
C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/actions/create_file.
rb:62:in `initialize': Permission denied @ rb_sysopen - C:/Rakefile (Errno::EACC
ES)
        from C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/actions
/create_file.rb:62:in `open'
        from C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/actions
/create_file.rb:62:in `block in invoke!'
        from C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/actions
/empty_directory.rb:116:in `call'
        from C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/actions
/empty_directory.rb:116:in `invoke_with_conflict_check'
        from C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/actions
/create_file.rb:60:in `invoke!'
        from C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/actions
.rb:94:in `action'
        from C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/actions
/create_file.rb:25:in `create_file'
        from C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/actions
/file_manipulation.rb:115:in `template'
        from C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/taza-0.9.2.1/lib/taza/genera

With that command I am running into the above error.

**Comment by uchagani** [comment]
@farooq33 I'll try to spin up a windows machine sometime this week and try it out.

**Comment by farooq33** [comment]
@uchagani sorry I bothered you,did u get a chance to set-up it

**Comment by uchagani** [comment]
Closing this as we haven't seen another response from @farooq33
