### ISSUE TITLE
Taza generator with error

### ISSUE THREAD

**Issue by vinchbr** [hammernight/taza#5]
Hi I'm using Ruby 2.0 (yes I know brave huh?)

I ran into two problems:

1 - gem i18n is necessary but not a dependency

2 - When running taza google I am getting
 undefined method `source_index' for Gem:Module

using taza 0.9.1.2

I am going to downgrade Ruby but just a heads up on compatibility with Ruby 2.0

**Comment by orieken** [comment]
this seems more like a rubygems issue, than a taza one based on this 
http://stackoverflow.com/questions/15349869/undefined-method-source-index-for-gemmodule-nomethoderror
